SET PAGESIZE 10000
SET LINESIZE 300
SET FEEDBACK OFF
SET HEADING ON
SET TRIMSPOOL ON
COLUMN NM_KECAMATAN FORMAT A25
COLUMN NM_KELURAHAN FORMAT A30
COLUMN KD_KEC FORMAT A10
COLUMN KD_KEL FORMAT A10

SELECT k.KD_KECAMATAN AS KD_KEC,
       k.KD_KELURAHAN AS KD_KEL,
       UPPER(REPLACE(kec.NM_KECAMATAN, ' ', '')) AS NM_KECAMATAN,
       UPPER(REPLACE(k.NM_KELURAHAN, ' ', '')) AS NM_KELURAHAN
FROM REF_KELURAHAN k
JOIN REF_KECAMATAN kec ON k.KD_PROPINSI = kec.KD_PROPINSI 
    AND k.KD_DATI2 = kec.KD_DATI2 
    AND k.KD_KECAMATAN = kec.KD_KECAMATAN
ORDER BY k.KD_KECAMATAN, k.KD_KELURAHAN;
EXIT;
