-- Update coordinates with accurate centroids from BPRD GeoJSON boundaries
-- Generated by generate_accurate_coordinates.py

UPDATE pbjt_assessments SET latitude = -8.12513321, longitude = 113.2226863 WHERE kelurahan = 'TOMPOKERSAN' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.12802648, longitude = 113.23716175 WHERE kelurahan = 'ROGOTRUNAN' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.13637158, longitude = 113.23832775 WHERE kelurahan = 'JOGOYUDAN' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.14503533, longitude = 113.22073521 WHERE kelurahan = 'DITOTRUNAN' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.139063, longitude = 113.19836497 WHERE kelurahan = 'LABRUK LOR' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.12930973, longitude = 113.21269721 WHERE kelurahan = 'CITRODIWANGSAN' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.15245677, longitude = 113.2650347 WHERE kelurahan = 'DENOK' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.13911679, longitude = 113.268652 WHERE kelurahan = 'BLUKON' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.13423799, longitude = 113.2595433 WHERE kelurahan = 'BORENG' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.22328836, longitude = 113.05461509 WHERE kelurahan = 'YUGOSARI' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.16695331, longitude = 113.0505413 WHERE kelurahan = 'SUMBER REJO' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.20500541, longitude = 113.09243862 WHERE kelurahan = 'J A R I T' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.1837973, longitude = 113.03427949 WHERE kelurahan = 'SUMBERWULUH' AND business_id LIKE 'BIZ-%';
UPDATE pbjt_assessments SET latitude = -8.14167076, longitude = 113.04077527 WHERE kelurahan = 'PENANGGAL' AND business_id LIKE 'BIZ-%';

-- Verify updates
SELECT 
    kelurahan,
    COUNT(*) as total,
    AVG(latitude) as avg_lat,
    AVG(longitude) as avg_lon
FROM pbjt_assessments 
WHERE business_id LIKE 'BIZ-%' AND kelurahan IN (
    'TOMPOKERSAN', 'ROGOTRUNAN', 'JOGOYUDAN', 'DITOTRUNAN', 'LABRUK LOR',
    'CITRODIWANGSAN', 'DENOK', 'BLUKON', 'BORENG', 'YUGOSARI',
    'SUMBER REJO', 'J A R I T', 'SUMBERWULUH', 'PENANGGAL'
)
GROUP BY kelurahan
ORDER BY kelurahan;
